### ISSUE TITLE
Whats wrong with your calendar

### ISSUE THREAD

**Issue by patchthecode** [WesBosman/CalendarProject#2]
1. Why are you tracking which date is selected?
   This is already done for you. `CellState.selected` is what you should use to know if a cell is selected or not.
2. Your weekday code is a little confusing. You might want to re-write it

I made some changes to your code here. The code is still not great in terms of architecture, but I just tried to fix the the errors you were having.

[CalendarProject.zip](https://github.com/WesBosman/CalendarProject/files/373296/CalendarProject.zip)

**Comment by WesBosman** [comment]
Thank you, the code that you have written is much simpler. I was pretty sure my logic was what was messing things up because the dates, columns and rows of the cells were all correct. I will work on refactoring my code. Really love this calendar thank you for the quick reply!

**Comment by patchthecode** [comment]
no problem 👍 
Also, the main error in your code that was causing the colors to change was your drawRect code.

This code is only executed once when the cell is created.
The problem occurs because you need to recall the drawRect every time the cell is about to be displayed. Remember, this calendar is a UICollecitonView, therefore cells are being reused. If you do not update your view, then old colors will appear all over the place. So I basically forced your dractRect to be called by calling the function setNeedsDisplay()

only one thing however that seems to be a real error calendar error.

A horizontal calendar should **not** be scrolled vertically.

I see that in your project, when the calendar is added to a viewController that is backed by a TabbarController, this causes the calendar to bounce vertically when you are scrolling.

This should not happen. 
I will look to see how i can get rid of this.
cheers.

**Comment by patchthecode** [comment]
And finally, your project was not building because you deleted the pod :/ 

I had to reinstall it.
1. pod init
2. edit the pod file to have JTAppleCalendar
3. pod install
4. run the workspace

Also, many of the things you are setting up in viewDidLoad() are already the calendar defaults.
So i removed them.

**Comment by WesBosman** [comment]
Having the view in a TabBarController explains why changing the cells itemsize doesn't affect the cells height but it will change the cells width. If I remember correctly though there was an example posted where someone had put their calendar in a TabBarController and the cells were still square. I think that person created a calendar for scheduling flight times. His calendar did not seem to bounce vertically.  I will see if I can figure a solution for that as well. 

With the drawRect code would you suggest placing another view behind the cells dayLabel and drawing on that view instead? 

I noticed last night that I was missing a lot of my resources in my podfile I don't know what happened there but I restored them as well and everything is working for me now.

**Comment by patchthecode** [comment]
Nah.
The itemSize behavior was intentionally coded by myself.  If your calendar is horizontal, then it will change the cells width. And if it is vertical, it will change its height.

But changing the itemSize and the size of the calendarView on storyBoard, you can make a square.
I can update it to be able to set the height and the width independently.  

but before i do this, let me know,
Is the current behavior creating problems for you?

**Comment by WesBosman** [comment]
No the current behavior is not creating problems for me. I am fine with the calendar as it is. I will try resizing the view in the storyboard until I get the desired result.

**Comment by WesBosman** [comment]
Hey, 

I had a few questions for you and when you closed the issue today it reminded me to ask you. I was wondering if the issue of having the calendar in a UIView inside a tab bar controller had been solved. Specifically the problem of the calendar accidentally scrolling vertically when the calendar was only supposed to scroll horizontally. I put my calendar view inside of a navigation controller that is inside the tab bar controller and this worked for stopping the vertical scrolling and bouncing but ultimately I would like to put this into a different container like a stack view. What do you suggest? 

My other question that I wanted to know is how most of the developers that have featured calendars dealt with displaying information from a particular date? I was wondering if it would be best to put a table view under my calendar for displaying the events of a particular day. Please let me know if you have any suggestions regarding that idea. 

Again thank you for the framework it really is great.

**Comment by patchthecode** [comment]
1. The bouncing problem was fixed a long time ago.
Are you using JTappleCalendar version `6.1.1` ? You should now be able to put the calendar in what ever view you want.

2. You can display information however you want. some developers have used a table under the calendar like this one -> https://cloud.githubusercontent.com/assets/6205705/15713434/b6c8867e-2816-11e6-8b90-cd82caea28dd.gif
But you can do it however you want. What ever is best for your project. There is no right/wrong way to do it.

**Comment by WesBosman** [comment]
That is awesome! Yeah I really like that guy's calendar. I think I am near 6.1.1 but I will update if need be. Thanks for taking the time to answer my questions. I will close the issue now.

**Comment by patchthecode** [comment]
What version are you using?
I need to know if you are still experiencing this.

**Comment by WesBosman** [comment]
I am no longer experiencing the bouncing when placing the calendar inside of a tab bar controller. I am using 6.0.1 currently.

**Comment by patchthecode** [comment]
awesome!
have a good one.
If you have any other issues, let me know.

**Comment by patchthecode** [comment]
Update when you get the chance. Many changes were made.
6.1.1 is extremely stable.

however, some function name might/might not have been changed.
But no worries, they are easy to find. And i can help you if you need.
